#!/usr/bin/env python3
"""
Generate HTML digest from a JSON paper list.
Creates a daily page and updates monthly/main index.
"""

import argparse
import json
import os
import re
from datetime import datetime, timedelta
from pathlib import Path

PAPERS_DIR = Path(__file__).parent.parent / "papers"

HTML_HEAD = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
  :root {{
    --bg: #f8f9fa; --card: #fff; --border: #e1e4e8;
    --text: #24292e; --muted: #6a737d; --accent: #0366d6;
    --tag-ma: #d4f0d4; --tag-ai: #d4e8f0; --tag-lg: #f0e8d4;
    --tag-hf: #ffd4e8; --tag-tr: #e8d4ff;
    --high: #28a745; --med: #f6a623; --low: #959da5;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
         background: var(--bg); color: var(--text); line-height: 1.6; }}
  .container {{ max-width: 960px; margin: 0 auto; padding: 24px 16px; }}
  header {{ border-bottom: 1px solid var(--border); padding-bottom: 16px; margin-bottom: 24px; }}
  header h1 {{ font-size: 1.5rem; }}
  header p {{ color: var(--muted); font-size: 0.9rem; margin-top: 4px; }}
  nav a {{ color: var(--accent); text-decoration: none; margin-right: 12px; font-size: 0.9rem; }}
  .quick-nav {{ display: flex; gap: 8px; flex-wrap: wrap; margin-top: 14px; }}
  .quick-nav a {{ display: inline-flex; align-items: center; justify-content: center;
                  min-height: 34px; padding: 6px 12px; border: 1px solid var(--border);
                  border-radius: 6px; background: var(--card); color: var(--accent);
                  text-decoration: none; font-size: 0.86rem; font-weight: 600; }}
  .quick-nav a:hover {{ border-color: var(--accent); background: #f1f7ff; }}
  .stats {{ display: flex; gap: 16px; margin: 16px 0; flex-wrap: wrap; }}
  .stat {{ background: var(--card); border: 1px solid var(--border); border-radius: 6px;
           padding: 8px 16px; font-size: 0.85rem; }}
  .stat span {{ font-weight: 600; color: var(--accent); }}
  .section-title {{ font-size: 1.1rem; font-weight: 600; margin: 24px 0 12px;
                    padding-bottom: 6px; border-bottom: 2px solid var(--border); }}
  .paper-card {{ background: var(--card); border: 1px solid var(--border); border-radius: 8px;
                 padding: 16px; margin-bottom: 12px; }}
  .paper-card:hover {{ box-shadow: 0 2px 8px rgba(0,0,0,0.08); }}
  .paper-title {{ font-size: 1rem; font-weight: 600; margin-bottom: 4px; }}
  .paper-title a {{ color: var(--text); text-decoration: none; }}
  .paper-title a:hover {{ color: var(--accent); }}
  .paper-meta {{ font-size: 0.8rem; color: var(--muted); margin-bottom: 8px; }}
  .tags {{ display: flex; flex-wrap: wrap; gap: 4px; margin-bottom: 10px; }}
  .tag {{ font-size: 0.72rem; padding: 2px 8px; border-radius: 12px; font-weight: 500; }}
  .tag-ma {{ background: var(--tag-ma); }}
  .tag-ai {{ background: var(--tag-ai); }}
  .tag-lg {{ background: var(--tag-lg); }}
  .tag-hf {{ background: var(--tag-hf); }}
  .tag-tr {{ background: var(--tag-tr); }}
  .tag-kw {{ background: #f0f0f0; }}
  .relevance {{ display: inline-block; font-size: 0.75rem; font-weight: 600; padding: 2px 8px;
               border-radius: 4px; margin-left: 6px; }}
  .rel-high {{ background: #e6f4ea; color: var(--high); }}
  .rel-med  {{ background: #fff8e1; color: var(--med); }}
  .rel-low  {{ background: #f6f8fa; color: var(--low); }}
  .summary-en {{ font-size: 0.88rem; color: #444; margin-bottom: 8px; line-height: 1.55; }}
  .summary-zh {{ font-size: 0.88rem; color: #333; background: #f6f8fa; border-left: 3px solid var(--border);
                 padding: 8px 12px; border-radius: 0 4px 4px 0; line-height: 1.6; }}
  .summary-zh-label {{ font-size: 0.75rem; color: var(--muted); margin-bottom: 2px; font-weight: 600; }}
  .paper-links {{ margin-top: 10px; font-size: 0.8rem; }}
  .paper-links a {{ color: var(--accent); text-decoration: none; margin-right: 12px; }}
  .no-paper {{ color: var(--muted); font-size: 0.9rem; padding: 16px; text-align: center; }}
  .back-top {{ position: fixed; right: 18px; bottom: 18px; display: inline-flex;
               align-items: center; justify-content: center; min-width: 42px; min-height: 42px;
               padding: 8px 10px; border-radius: 6px; background: var(--accent);
               color: #fff; text-decoration: none; font-size: 0.85rem; font-weight: 600;
               box-shadow: 0 2px 8px rgba(0,0,0,0.18); }}
  .back-top:hover {{ background: #024f9d; }}
  footer {{ margin-top: 40px; padding-top: 16px; border-top: 1px solid var(--border);
            font-size: 0.8rem; color: var(--muted); text-align: center; }}
</style>
</head>
<body>
<div id="top" class="container">
"""

HTML_FOOT = """
<footer>
  <p>Generated by Codex · Paper Reading Collection · Multi-Agent Efficiency &amp; Communication</p>
</footer>
</div>
</body>
</html>
"""


def relevance_label(score: int) -> tuple[str, str]:
    if score >= 6:
        return "high", "★ 高度相关"
    elif score >= 3:
        return "med", "◆ 相关"
    else:
        return "low", "· 低相关"


def category_tag(cat: str) -> str:
    mapping = {
        "cs.MA": ("tag-ma", "cs.MA"),
        "cs.AI": ("tag-ai", "cs.AI"),
        "cs.LG": ("tag-lg", "cs.LG"),
        "cs.CL": ("tag-ai", "cs.CL"),
        "HF Daily": ("tag-hf", "HF精选"),
    }
    cls, label = mapping.get(cat, ("tag-kw", cat))
    return f'<span class="tag {cls}">{label}</span>'


KEYWORD_LABELS = [
    ("single_vs_multi", "single-vs-multi"),
    ("agent_communication", "agent communication"),
    ("single-agent vs multi-agent", "single-vs-multi"),
    ("single agent vs multi agent", "single-vs-multi"),
    ("single-agent versus multi-agent", "single-vs-multi"),
    ("single agent versus multi agent", "single-vs-multi"),
    ("single-agent", "single-agent"),
    ("single agent", "single-agent"),
    ("heterogeneous agents", "heterogeneous agents"),
    ("heterogeneous multi-agent", "heterogeneous agents"),
    ("homogeneous agents", "homogeneous agents"),
    ("role specialization", "role specialization"),
    ("division of labor", "division of labor"),
    ("agent-agent communication", "agent-agent communication"),
    ("inter-agent communication", "inter-agent communication"),
    ("agent communication", "agent communication"),
    ("communication protocol", "communication protocol"),
    ("communication efficiency", "communication cost"),
    ("communication bandwidth", "communication cost"),
    ("message passing", "message passing"),
    ("emergent communication", "emergent communication"),
    ("natural language communication", "language communication"),
    ("agent dialogue", "language communication"),
    ("agent conversation", "language communication"),
    ("multimodal communication", "multimodal communication"),
    ("symbolic communication", "symbolic communication"),
    ("non-verbal communication", "non-text communication"),
    ("shared memory", "shared memory"),
    ("blackboard", "shared memory"),
    ("multi-agent debate", "multi-agent debate"),
    ("multi-agent discussion", "multi-agent discussion"),
]


def clean_keywords(keywords: list[str], limit: int) -> list[str]:
    """Normalize and de-duplicate short display keywords."""
    seen = set()
    cleaned = []
    for keyword in keywords:
        label = keyword.strip().lower()
        if not label or label in seen:
            continue
        seen.add(label)
        cleaned.append(label)
        if len(cleaned) >= limit:
            break
    return cleaned


def paper_keywords(paper: dict, limit: int = 4) -> list[str]:
    """Derive compact topic labels for one paper."""
    labels = []
    labels.extend(paper.get("topic_keywords", []))
    labels.extend(paper.get("focus_tracks", []))
    if paper.get("focus_track"):
        labels.append(paper["focus_track"])

    relevance = paper.get("relevance", {})
    track_matches = relevance.get("track_matches", {})
    for track, matches in track_matches.items():
        if matches:
            labels.append(track)
            labels.extend(matches)
    labels.extend(relevance.get("primary_matches", []))
    labels.extend(relevance.get("secondary_matches", []))

    display = []
    for label in labels:
        normalized = label.strip().lower()
        mapped = next((display for key, display in KEYWORD_LABELS if key == normalized), normalized)
        display.append(mapped)
    return clean_keywords(display, limit)


def digest_keywords(papers: list[dict], limit: int = 3) -> list[str]:
    """Pick the most representative labels for a daily digest."""
    weights = {}
    priority = []
    for paper in papers:
        score = paper.get("relevance", {}).get("score", 0)
        weight = 3 if score >= 6 else 2 if score >= 3 else 1
        keywords = paper_keywords(paper, limit=4)
        for track_keyword in ("single-vs-multi", "agent communication"):
            if track_keyword in keywords and track_keyword not in priority:
                priority.append(track_keyword)
        for keyword in keywords:
            weights[keyword] = weights.get(keyword, 0) + weight
    ranked = sorted(weights.items(), key=lambda item: (-item[1], item[0]))
    labels = priority + [keyword for keyword, _ in ranked if keyword not in priority]
    return labels[:limit]


def extract_title_keywords(html_file: Path) -> list[str]:
    """Read keywords from a generated daily page title when building indexes."""
    try:
        text = html_file.read_text(encoding="utf-8")
    except OSError:
        return []
    match = re.search(r"<h1>.*?·\s*\d{4}年\d{2}月\d{2}日(?:\s*·\s*(.*?))?</h1>", text, re.S)
    if not match or not match.group(1):
        return []
    raw = re.sub(r"<.*?>", "", match.group(1)).strip()
    return clean_keywords([part.strip() for part in raw.split(" / ")], 3)


def generate_daily_html(data: dict, date_str: str) -> str:
    papers = data.get("papers", [])
    hf_daily_papers = data.get("hf_daily_papers", [])
    hf_daily_ids = {p.get("id") for p in hf_daily_papers}
    dt = datetime.strptime(date_str, "%Y-%m-%d")
    date_display = dt.strftime("%Y年%m月%d日")
    date_en = dt.strftime("%B %d, %Y")
    keywords = digest_keywords(papers)
    keyword_text = " / ".join(keywords)
    keyword_suffix = f" · {keyword_text}" if keyword_text else ""

    high = [p for p in papers if p["relevance"]["score"] >= 6]
    med = [p for p in papers if 3 <= p["relevance"]["score"] < 6
           and not p["relevance"].get("is_tech_report")]
    tech_reports = [p for p in papers if p["relevance"].get("is_tech_report")]
    fetched_at = data.get("fetched_at", "")

    prev_dt = dt - timedelta(days=1)
    next_dt = dt + timedelta(days=1)

    def day_href(d):
        m = d.strftime("%Y-%m")
        return f"{d.strftime('%Y-%m-%d')}.html" if m == date_str[:7] else f"../{m}/{d.strftime('%Y-%m-%d')}.html"

    prev_href = day_href(prev_dt)
    next_href = day_href(next_dt)
    prev_label = prev_dt.strftime("%m-%d")
    next_label = next_dt.strftime("%m-%d")

    html = HTML_HEAD.format(title=f"论文日报 {date_str}{keyword_suffix}")
    html += f"""
<header>
  <h1>📄 论文日报 · {date_display}{keyword_suffix}</h1>
  <p>Daily Paper Digest · {date_en} · single-vs-multi agents &amp; agent-agent communication</p>
  <nav style="margin-top:10px;display:flex;align-items:center;gap:12px;flex-wrap:wrap">
    <a href="{prev_href}">← {prev_label}</a>
    <a href="../index.html">主页</a>
    <a href="index.html">本月</a>
    <a href="{next_href}">{next_label} →</a>
  </nav>
  <div class="quick-nav">
    <a href="#related-papers">相关 Papers</a>
    <a href="#hf-daily">HF Daily</a>
  </div>
</header>

<div class="stats">
  <div class="stat">总计 <span>{len(papers)}</span> 篇</div>
  <div class="stat">高度相关 <span>{len(high)}</span> 篇</div>
  <div class="stat">相关 <span>{len(med)}</span> 篇</div>
  <div class="stat">HF Daily <span>{len(hf_daily_papers)}</span> 篇</div>
  <div class="stat">技术报告 <span>{len(tech_reports)}</span> 篇</div>
  <div class="stat" style="color:var(--muted)">更新于 {fetched_at[:16].replace("T"," ")} UTC</div>
</div>
"""

    def render_paper(p: dict, show_relevance: bool = True) -> str:
        rel_cls, rel_label = relevance_label(p["relevance"]["score"])
        authors_list = p.get("authors", [])
        authors = ", ".join(authors_list[:4])
        if len(authors_list) > 4:
            authors += " et al."
        cats = p.get("categories", [p.get("primary_category", "")])
        tag_html = "".join(category_tag(c) for c in cats[:3] if c)
        if p.get("hf_daily"):
            tag_html += category_tag("HF Daily")
        if p["relevance"].get("is_tech_report"):
            tag_html += '<span class="tag tag-tr">Tech Report</span>'
        for keyword in paper_keywords(p):
            tag_html += f'<span class="tag tag-kw">{keyword}</span>'
        kws = p["relevance"]["primary_matches"][:3]
        for kw in kws:
            if kw not in paper_keywords(p):
                tag_html += f'<span class="tag tag-kw">{kw}</span>'

        summary_en = p.get("summary_en", "")
        summary_zh = p.get("summary_zh", "")

        card = f"""
<div class="paper-card">
  <div class="paper-title">
    <a href="{p['url']}" target="_blank">{p['title']}</a>
"""
        if show_relevance:
            card += f'    <span class="relevance rel-{rel_cls}">{rel_label}</span>\n'
        elif p.get("hf_daily_module"):
            card += '    <span class="relevance rel-med">HF Daily</span>\n'
        card += f"""  </div>
  <div class="paper-meta">{authors} · {p.get('published','')[:10]}</div>
  <div class="tags">{tag_html}</div>
"""
        if summary_en:
            card += f'  <div class="summary-en">{summary_en}</div>\n'
        else:
            abstract_short = p["abstract"][:300] + ("..." if len(p["abstract"]) > 300 else "")
            card += f'  <div class="summary-en">{abstract_short}</div>\n'

        if summary_zh:
            card += f'  <div class="summary-zh-label">中文摘要</div>\n'
            card += f'  <div class="summary-zh">{summary_zh}</div>\n'

        card += f"""  <div class="paper-links">
    <a href="{p['url']}" target="_blank">📄 Abstract</a>
    <a href="{p['pdf_url']}" target="_blank">📥 PDF</a>
  </div>
</div>"""
        return card

    # Section: Hugging Face Daily broad picks
    if hf_daily_papers:
        html += '<div id="hf-daily" class="section-title">🤗 Hugging Face Daily / Broad Picks</div>\n'
        for p in hf_daily_papers:
            html += render_paper(p, show_relevance=False)

    # Section: High relevance
    if high:
        html += '<div id="related-papers" class="section-title">⭐ 高度相关 / Highly Relevant</div>\n'
        for p in high:
            html += render_paper(p)

    # Section: Tech reports
    tech_not_in_high = [p for p in tech_reports if p["relevance"]["score"] < 6]
    if tech_not_in_high:
        html += '<div class="section-title">🏢 技术报告 / Tech Reports</div>\n'
        for p in tech_not_in_high:
            html += render_paper(p)

    # Section: Medium relevance
    if med:
        title_id = "" if high else ' id="related-papers"'
        html += f'<div{title_id} class="section-title">◆ 相关 / Relevant</div>\n'
        for p in med:
            html += render_paper(p)

    # Section: Others (low score, for reference)
    low = [p for p in papers if p["relevance"]["score"] < 3
           and not p["relevance"].get("is_tech_report")
           and p.get("id") not in hf_daily_ids]
    if low:
        html += '<div class="section-title" style="color:var(--muted)">· 其他 / Others</div>\n'
        for p in low[:20]:  # cap at 20
            html += render_paper(p)
        if len(low) > 20:
            html += f'<div class="no-paper">... 还有 {len(low)-20} 篇低相关文章未显示</div>\n'

    if not papers:
        html += '<div class="no-paper">该日期暂无收录文章</div>\n'

    html += '<a class="back-top" href="#top">顶部</a>\n'
    html += HTML_FOOT
    return html


def update_monthly_index(month_dir: Path, date_str: str, paper_count: int, high_count: int, keywords: list[str]):
    """Add or update a date entry in the monthly index."""
    entries = []
    index_path = month_dir / "index.html"
    month = date_str[:7]
    dt = datetime.strptime(month, "%Y-%m")
    month_display = dt.strftime("%Y年%m月")

    # Collect existing date entries from directory
    for html_file in sorted(month_dir.glob("????-??-??.html"), reverse=True):
        d = html_file.stem
        if d == date_str:
            entries.append((d, paper_count, high_count, keywords))
        else:
            entries.append((d, None, None, extract_title_keywords(html_file)))

    html = HTML_HEAD.format(title=f"{month_display} 论文索引")
    html += f"""
<header>
  <h1>📅 {month_display} · 论文索引</h1>
  <nav style="margin-top:10px"><a href="../index.html">← 主页</a></nav>
</header>
<div style="display:flex;flex-direction:column;gap:8px;margin-top:16px">
"""
    for d, cnt, hcnt, kws in entries:
        dt2 = datetime.strptime(d, "%Y-%m-%d")
        label = dt2.strftime("%m月%d日 (%a)")
        cnt_str = f" · {cnt}篇 · {hcnt}高相关" if cnt is not None else ""
        kw_str = f" · {' / '.join(kws)}" if kws else ""
        html += f'  <a href="{d}.html" style="padding:10px 14px;background:#fff;border:1px solid var(--border);border-radius:6px;text-decoration:none;color:var(--text)">{label}{kw_str}{cnt_str}</a>\n'

    html += "</div>\n" + HTML_FOOT
    index_path.write_text(html, encoding="utf-8")


def update_main_index():
    """Rebuild main index from all monthly directories."""
    months = sorted(
        [d for d in PAPERS_DIR.iterdir() if d.is_dir() and d.name[:4].isdigit()],
        reverse=True,
    )
    html = HTML_HEAD.format(title="论文日报 · 主页")
    html += """
<header>
  <h1>📚 Multi-Agent 论文日报</h1>
  <p>聚焦 single-vs-multi agents 与 agent-agent communication · Daily paper digest on agent settings, heterogeneity, and communication forms</p>
</header>
"""
    # Show recent daily entries (last 14)
    recent = []
    for month_dir in months:
        for f in sorted(month_dir.glob("????-??-??.html"), reverse=True):
            recent.append((f.stem, month_dir.name, f))
            if len(recent) >= 14:
                break
        if len(recent) >= 14:
            break

    if recent:
        html += '<div class="section-title">最近更新 / Recent Updates</div>\n'
        html += '<div style="display:flex;flex-direction:column;gap:8px">\n'
        for d, month, f in recent:
            dt2 = datetime.strptime(d, "%Y-%m-%d")
            label = dt2.strftime("%Y年%m月%d日 (%a)")
            kws = extract_title_keywords(f)
            kw_str = f" · {' / '.join(kws)}" if kws else ""
            html += f'  <a href="{month}/{d}.html" style="padding:10px 14px;background:#fff;border:1px solid var(--border);border-radius:6px;text-decoration:none;color:var(--text)">{label}{kw_str}</a>\n'
        html += "</div>\n"

    if months:
        html += '<div class="section-title" style="margin-top:24px">按月浏览 / Browse by Month</div>\n'
        html += '<div style="display:flex;gap:8px;flex-wrap:wrap">\n'
        for month_dir in months:
            dt2 = datetime.strptime(month_dir.name, "%Y-%m")
            label = dt2.strftime("%Y年%m月")
            html += f'  <a href="{month_dir.name}/index.html" style="padding:8px 16px;background:#fff;border:1px solid var(--border);border-radius:6px;text-decoration:none;color:var(--text)">{label}</a>\n'
        html += "</div>\n"

    html += HTML_FOOT
    (PAPERS_DIR / "index.html").write_text(html, encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description="Generate HTML from paper JSON")
    parser.add_argument("json_file", help="Input JSON file from fetch_papers.py")
    parser.add_argument("--date", help="Date override YYYY-MM-DD")
    args = parser.parse_args()

    with open(args.json_file, encoding="utf-8") as f:
        data = json.load(f)

    date_str = args.date or data["date"]
    month = date_str[:7]

    month_dir = PAPERS_DIR / month
    month_dir.mkdir(parents=True, exist_ok=True)

    html = generate_daily_html(data, date_str)
    out_path = month_dir / f"{date_str}.html"
    out_path.write_text(html, encoding="utf-8")
    print(f"[info] Written: {out_path}")

    high_count = len([p for p in data["papers"] if p["relevance"]["score"] >= 6])
    update_monthly_index(month_dir, date_str, len(data["papers"]), high_count, digest_keywords(data["papers"]))
    update_main_index()
    print(f"[info] Indexes updated")


if __name__ == "__main__":
    main()
