#!/usr/bin/env python3
"""
Generate HTML digest from a JSON paper list.
Creates a daily page and updates monthly/main index.
"""

import argparse
import json
import os
from datetime import datetime
from pathlib import Path

PAPERS_DIR = Path(__file__).parent.parent / "papers"

HTML_HEAD = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
  :root {{
    --bg: #f8f9fa; --card: #fff; --border: #e1e4e8;
    --text: #24292e; --muted: #6a737d; --accent: #0366d6;
    --tag-ma: #d4f0d4; --tag-ai: #d4e8f0; --tag-lg: #f0e8d4;
    --tag-hf: #ffd4e8; --tag-tr: #e8d4ff;
    --high: #28a745; --med: #f6a623; --low: #959da5;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
         background: var(--bg); color: var(--text); line-height: 1.6; }}
  .container {{ max-width: 960px; margin: 0 auto; padding: 24px 16px; }}
  header {{ border-bottom: 1px solid var(--border); padding-bottom: 16px; margin-bottom: 24px; }}
  header h1 {{ font-size: 1.5rem; }}
  header p {{ color: var(--muted); font-size: 0.9rem; margin-top: 4px; }}
  nav a {{ color: var(--accent); text-decoration: none; margin-right: 12px; font-size: 0.9rem; }}
  .stats {{ display: flex; gap: 16px; margin: 16px 0; flex-wrap: wrap; }}
  .stat {{ background: var(--card); border: 1px solid var(--border); border-radius: 6px;
           padding: 8px 16px; font-size: 0.85rem; }}
  .stat span {{ font-weight: 600; color: var(--accent); }}
  .section-title {{ font-size: 1.1rem; font-weight: 600; margin: 24px 0 12px;
                    padding-bottom: 6px; border-bottom: 2px solid var(--border); }}
  .paper-card {{ background: var(--card); border: 1px solid var(--border); border-radius: 8px;
                 padding: 16px; margin-bottom: 12px; }}
  .paper-card:hover {{ box-shadow: 0 2px 8px rgba(0,0,0,0.08); }}
  .paper-title {{ font-size: 1rem; font-weight: 600; margin-bottom: 4px; }}
  .paper-title a {{ color: var(--text); text-decoration: none; }}
  .paper-title a:hover {{ color: var(--accent); }}
  .paper-meta {{ font-size: 0.8rem; color: var(--muted); margin-bottom: 8px; }}
  .tags {{ display: flex; flex-wrap: wrap; gap: 4px; margin-bottom: 10px; }}
  .tag {{ font-size: 0.72rem; padding: 2px 8px; border-radius: 12px; font-weight: 500; }}
  .tag-ma {{ background: var(--tag-ma); }}
  .tag-ai {{ background: var(--tag-ai); }}
  .tag-lg {{ background: var(--tag-lg); }}
  .tag-hf {{ background: var(--tag-hf); }}
  .tag-tr {{ background: var(--tag-tr); }}
  .tag-kw {{ background: #f0f0f0; }}
  .relevance {{ display: inline-block; font-size: 0.75rem; font-weight: 600; padding: 2px 8px;
               border-radius: 4px; margin-left: 6px; }}
  .rel-high {{ background: #e6f4ea; color: var(--high); }}
  .rel-med  {{ background: #fff8e1; color: var(--med); }}
  .rel-low  {{ background: #f6f8fa; color: var(--low); }}
  .summary-en {{ font-size: 0.88rem; color: #444; margin-bottom: 8px; line-height: 1.55; }}
  .summary-zh {{ font-size: 0.88rem; color: #333; background: #f6f8fa; border-left: 3px solid var(--border);
                 padding: 8px 12px; border-radius: 0 4px 4px 0; line-height: 1.6; }}
  .summary-zh-label {{ font-size: 0.75rem; color: var(--muted); margin-bottom: 2px; font-weight: 600; }}
  .paper-links {{ margin-top: 10px; font-size: 0.8rem; }}
  .paper-links a {{ color: var(--accent); text-decoration: none; margin-right: 12px; }}
  .no-paper {{ color: var(--muted); font-size: 0.9rem; padding: 16px; text-align: center; }}
  footer {{ margin-top: 40px; padding-top: 16px; border-top: 1px solid var(--border);
            font-size: 0.8rem; color: var(--muted); text-align: center; }}
</style>
</head>
<body>
<div class="container">
"""

HTML_FOOT = """
<footer>
  <p>Generated by Claude · Paper Reading Collection · Multi-Agent Efficiency &amp; Communication</p>
</footer>
</div>
</body>
</html>
"""


def relevance_label(score: int) -> tuple[str, str]:
    if score >= 6:
        return "high", "★ 高度相关"
    elif score >= 3:
        return "med", "◆ 相关"
    else:
        return "low", "· 低相关"


def category_tag(cat: str) -> str:
    mapping = {
        "cs.MA": ("tag-ma", "cs.MA"),
        "cs.AI": ("tag-ai", "cs.AI"),
        "cs.LG": ("tag-lg", "cs.LG"),
        "HF Daily": ("tag-hf", "HF精选"),
    }
    cls, label = mapping.get(cat, ("tag-kw", cat))
    return f'<span class="tag {cls}">{label}</span>'


def generate_daily_html(data: dict, date_str: str) -> str:
    papers = data.get("papers", [])
    dt = datetime.strptime(date_str, "%Y-%m-%d")
    date_display = dt.strftime("%Y年%m月%d日")
    date_en = dt.strftime("%B %d, %Y")

    high = [p for p in papers if p["relevance"]["score"] >= 6]
    med = [p for p in papers if 3 <= p["relevance"]["score"] < 6]
    tech_reports = [p for p in papers if p["relevance"].get("is_tech_report")]
    fetched_at = data.get("fetched_at", "")

    html = HTML_HEAD.format(title=f"论文日报 {date_str}")
    html += f"""
<header>
  <h1>📄 论文日报 · {date_display}</h1>
  <p>Daily Paper Digest · {date_en}</p>
  <nav style="margin-top:10px">
    <a href="../index.html">← 主页</a>
    <a href="index.html">← 本月</a>
  </nav>
</header>

<div class="stats">
  <div class="stat">总计 <span>{len(papers)}</span> 篇</div>
  <div class="stat">高度相关 <span>{len(high)}</span> 篇</div>
  <div class="stat">相关 <span>{len(med)}</span> 篇</div>
  <div class="stat">技术报告 <span>{len(tech_reports)}</span> 篇</div>
  <div class="stat" style="color:var(--muted)">更新于 {fetched_at[:16].replace("T"," ")} UTC</div>
</div>
"""

    def render_paper(p: dict) -> str:
        rel_cls, rel_label = relevance_label(p["relevance"]["score"])
        authors = ", ".join(p["authors"][:4])
        if len(p["authors"]) > 4:
            authors += " et al."
        cats = p.get("categories", [p.get("primary_category", "")])
        tag_html = "".join(category_tag(c) for c in cats[:3] if c)
        if p.get("hf_daily"):
            tag_html += category_tag("HF Daily")
        if p["relevance"].get("is_tech_report"):
            tag_html += '<span class="tag tag-tr">Tech Report</span>'
        kws = p["relevance"]["primary_matches"][:3]
        for kw in kws:
            tag_html += f'<span class="tag tag-kw">{kw}</span>'

        summary_en = p.get("summary_en", "")
        summary_zh = p.get("summary_zh", "")

        card = f"""
<div class="paper-card">
  <div class="paper-title">
    <a href="{p['url']}" target="_blank">{p['title']}</a>
    <span class="relevance rel-{rel_cls}">{rel_label}</span>
  </div>
  <div class="paper-meta">{authors} · {p.get('published','')[:10]}</div>
  <div class="tags">{tag_html}</div>
"""
        if summary_en:
            card += f'  <div class="summary-en">{summary_en}</div>\n'
        else:
            abstract_short = p["abstract"][:300] + ("..." if len(p["abstract"]) > 300 else "")
            card += f'  <div class="summary-en">{abstract_short}</div>\n'

        if summary_zh:
            card += f'  <div class="summary-zh-label">中文摘要</div>\n'
            card += f'  <div class="summary-zh">{summary_zh}</div>\n'

        card += f"""  <div class="paper-links">
    <a href="{p['url']}" target="_blank">📄 Abstract</a>
    <a href="{p['pdf_url']}" target="_blank">📥 PDF</a>
  </div>
</div>"""
        return card

    # Section: High relevance
    if high:
        html += '<div class="section-title">⭐ 高度相关 / Highly Relevant</div>\n'
        for p in high:
            html += render_paper(p)

    # Section: Tech reports
    tech_not_in_high = [p for p in tech_reports if p["relevance"]["score"] < 6]
    if tech_not_in_high:
        html += '<div class="section-title">🏢 技术报告 / Tech Reports</div>\n'
        for p in tech_not_in_high:
            html += render_paper(p)

    # Section: Medium relevance
    if med:
        html += '<div class="section-title">◆ 相关 / Relevant</div>\n'
        for p in med:
            html += render_paper(p)

    # Section: Others (low score, for reference)
    low = [p for p in papers if p["relevance"]["score"] < 3]
    if low:
        html += '<div class="section-title" style="color:var(--muted)">· 其他 / Others</div>\n'
        for p in low[:20]:  # cap at 20
            html += render_paper(p)
        if len(low) > 20:
            html += f'<div class="no-paper">... 还有 {len(low)-20} 篇低相关文章未显示</div>\n'

    if not papers:
        html += '<div class="no-paper">该日期暂无收录文章</div>\n'

    html += HTML_FOOT
    return html


def update_monthly_index(month_dir: Path, date_str: str, paper_count: int, high_count: int):
    """Add or update a date entry in the monthly index."""
    entries = []
    index_path = month_dir / "index.html"
    month = date_str[:7]
    dt = datetime.strptime(month, "%Y-%m")
    month_display = dt.strftime("%Y年%m月")

    # Collect existing date entries from directory
    for html_file in sorted(month_dir.glob("????-??-??.html"), reverse=True):
        d = html_file.stem
        if d == date_str:
            entries.append((d, paper_count, high_count))
        else:
            entries.append((d, None, None))

    html = HTML_HEAD.format(title=f"{month_display} 论文索引")
    html += f"""
<header>
  <h1>📅 {month_display} · 论文索引</h1>
  <nav style="margin-top:10px"><a href="../index.html">← 主页</a></nav>
</header>
<div style="display:flex;flex-direction:column;gap:8px;margin-top:16px">
"""
    for d, cnt, hcnt in entries:
        dt2 = datetime.strptime(d, "%Y-%m-%d")
        label = dt2.strftime("%m月%d日 (%a)")
        cnt_str = f" · {cnt}篇 · {hcnt}高相关" if cnt is not None else ""
        html += f'  <a href="{d}.html" style="padding:10px 14px;background:#fff;border:1px solid var(--border);border-radius:6px;text-decoration:none;color:var(--text)">{label}{cnt_str}</a>\n'

    html += "</div>\n" + HTML_FOOT
    index_path.write_text(html, encoding="utf-8")


def update_main_index():
    """Rebuild main index from all monthly directories."""
    months = sorted(
        [d for d in PAPERS_DIR.iterdir() if d.is_dir() and d.name[:4].isdigit()],
        reverse=True,
    )
    html = HTML_HEAD.format(title="论文日报 · 主页")
    html += """
<header>
  <h1>📚 Multi-Agent 论文日报</h1>
  <p>专注于多智能体系统的效率与通信研究 · Daily paper digest on multi-agent efficiency &amp; communication</p>
</header>
"""
    # Show recent daily entries (last 14)
    recent = []
    for month_dir in months:
        for f in sorted(month_dir.glob("????-??-??.html"), reverse=True):
            recent.append((f.stem, month_dir.name, f))
            if len(recent) >= 14:
                break
        if len(recent) >= 14:
            break

    if recent:
        html += '<div class="section-title">最近更新 / Recent Updates</div>\n'
        html += '<div style="display:flex;flex-direction:column;gap:8px">\n'
        for d, month, f in recent:
            dt2 = datetime.strptime(d, "%Y-%m-%d")
            label = dt2.strftime("%Y年%m月%d日 (%a)")
            html += f'  <a href="{month}/{d}.html" style="padding:10px 14px;background:#fff;border:1px solid var(--border);border-radius:6px;text-decoration:none;color:var(--text)">{label}</a>\n'
        html += "</div>\n"

    if months:
        html += '<div class="section-title" style="margin-top:24px">按月浏览 / Browse by Month</div>\n'
        html += '<div style="display:flex;gap:8px;flex-wrap:wrap">\n'
        for month_dir in months:
            dt2 = datetime.strptime(month_dir.name, "%Y-%m")
            label = dt2.strftime("%Y年%m月")
            html += f'  <a href="{month_dir.name}/index.html" style="padding:8px 16px;background:#fff;border:1px solid var(--border);border-radius:6px;text-decoration:none;color:var(--text)">{label}</a>\n'
        html += "</div>\n"

    html += HTML_FOOT
    (PAPERS_DIR / "index.html").write_text(html, encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description="Generate HTML from paper JSON")
    parser.add_argument("json_file", help="Input JSON file from fetch_papers.py")
    parser.add_argument("--date", help="Date override YYYY-MM-DD")
    args = parser.parse_args()

    with open(args.json_file, encoding="utf-8") as f:
        data = json.load(f)

    date_str = args.date or data["date"]
    month = date_str[:7]

    month_dir = PAPERS_DIR / month
    month_dir.mkdir(parents=True, exist_ok=True)

    html = generate_daily_html(data, date_str)
    out_path = month_dir / f"{date_str}.html"
    out_path.write_text(html, encoding="utf-8")
    print(f"[info] Written: {out_path}")

    high_count = len([p for p in data["papers"] if p["relevance"]["score"] >= 6])
    update_monthly_index(month_dir, date_str, len(data["papers"]), high_count)
    update_main_index()
    print(f"[info] Indexes updated")


if __name__ == "__main__":
    main()
